### ISSUE TITLE
AltairZ80: VDM1 device

### ISSUE THREAD

**Issue by deltecent** [open-simh/simh#180]
I have a prototype VDM-1 device working with AltairZ80 using sim_video. I started the project in order to run Sol-20 software which seems to just work. I'm able to hex load SOLOS and then send ENT files using the SIMH console:

```
set ptr dis
set ptp dis
set hdsk dis
set mdsa ena
set vdm1 ena

attach mdsa0 CPM22b14-48K-SDC-SOL.NSI
load -h solos41.hex
g c000
```

After loading SOLOS:

```
> SET I=1
[paste ENT file on console]
> EX addr
```

<img width="585" alt="Screenshot 2023-02-15 at 6 18 31 PM" src="https://user-images.githubusercontent.com/24786756/219251685-4d824dd6-afdc-413a-bb9b-caeab325ab6c.png">

I've also been able to boot CP/M using the MDSA device.

<img width="595" alt="Screenshot 2023-02-15 at 6 33 32 PM" src="https://user-images.githubusercontent.com/24786756/219253322-65120df6-dd5a-42f2-8b95-f5213d76a9bc.png">

My question is how to add the video support to the AltairZ80 simulator without breaking the build for people that don't want it. I think there is some magic that happens in the makefile but I have not figured it out yet.

@markpizz - Looking for the right way to do this, if at all.

**Comment by markpizz** [comment]
From your above commands, what you've already got is setup so that people that don't want it won't get it since the VDM1 device is disabled by default. 

Near the top of the makefile, after the "ifneq (3,$(SIM_MAJOR))" there should be:
```
ifneq (,$(findstring altairz80,$(MAKECMDGOALS)))
  VIDEO_USEFUL = true
endif
```

Assuming that your device is using the APIs in display/display.h/.c

In the section  between ALTAIRZ80D and ALTAIRZ80_OPT, the dependent components in the ALTAIRZ80 list should have:   ``` ${DISPLAYL}``` added, and ALTAIRZ80_OPT should have ```${DISPLAY_OPT}``` added.

You should have some sort of code in the VDM1 DEVICE reset routine that doesn't allow the VDM1 device to be enabled if USE_DISPLAY isn't defined.  Look in imlac_crt.c for one way to do this.

That should be it.

If you're not using the display/display.h/.c APIs then please elaborate what you're actually doing.

- Mark

**Comment by deltecent** [comment]
I just found the `VIDEO_USEFUL` section in the makefile.

I don't believe I'm using the APIs in display/display.h/.c

I'm using the following APIs in sim_video.c/.h:

```
#include "sim_video.h"

vid_open_window (&vdm1_vptr, &vdm1_dev, "Display", VDM1_XSIZE, VDM1_YSIZE, 0);
vid_map_rgb_window (vdm1_vptr, 0x00, 0x00, 0x00);
vid_draw_window (vdm1_vptr, 0, 0, VDM1_XSIZE, VDM1_YSIZE, vdm1_surface);
vid_refresh_window (vdm1_vptr);
vid_poll_kb(&kev);
vid_close ();
```

**Comment by markpizz** [comment]
> I'm using the following APIs in sim_video.c/.h:

Then the ALTAIRZ80_OPT needs these additions:
```
${VIDEO_CCDEFS} ${VIDEO_LDFLAGS}
```
with nothing added to to the ALTAIRZ80 list.

You should still make enabling of the VDM1 DEVICE in the reset routine dependent on USE_SIM_VIDEO instead of USE_DISPLAY.  The general concept demonstrated in imlac_crt.c would still be a relevant example.

**Comment by hharte** [comment]
You could also #ifdef out the VDM1 device in altairz80_sys.c if USE_SIM_VIDEO is not defined. This way, it will not show up as a device if the simulator is built without video support.

**Comment by markpizz** [comment]
> You could also #ifdef out the VDM1 device in altairz80_sys.c if USE_SIM_VIDEO is not defined. This way, it will not show up as a device if the simulator is built without video support.

In general, I would avoid  doing that.

Leaving the DEVICE in the simulator's device list leaves the device connected to what SCP can see and thus what a user can engage.  The HELP for the device will be reachable and it could explain what the device does, and if it is disabled due to some missing build time component the help could explain that detail.  In fact, an effort to enable the device when video support is missing could produce a message saying that "video support is not currently built into the simulator".

Simply disabling it in altirz80_sys.c would save a maximum of 8 bytes of program size, which hardly seems significant.

**Comment by deltecent** [comment]
While we're on the subject, what is the difference between sim_video and display and is one better than the other?

**Comment by markpizz** [comment]
display sits on top of sim_video and therefore is implemented using sim_video APIs, so direct use of sim_video is potentially more efficient than display.  display was originally designed with support for phosphor intensity decay.

An example that uses display can be seen in action if you build the PDP11 simulator and:
```
sim> set VT enable
sim> boot VT
```

have fun.
