### ISSUE TITLE
SCP/AltairZ80: Throttle doesn't adjust UNIT wait times

### ISSUE THREAD

**Issue by deltecent** [open-simh/simh#184]
When throttle runs through all timers and adjust the calibration for each one that is running to reflect the throttle rate, the units aren't adjusted for the new throttle rate causing a large delay in the next execution of service routines.

The timing in SCP is beyond my understanding, but it seems the problem occurs here:

```
            /* Run through all timers and adjust the calibration for each */
            /* one that is running to reflect the throttle rate */
            for (tmr=0; tmr<=SIM_NTIMERS; tmr++) {
                rtc = &rtcs[tmr];                                   
                if (rtc->hz) {                                      /* running? */
                    SHOW_QUEUE();
                    rtc->currd = (int32)(sim_throt_cps / rtc->hz);/* use throttle calibration */
                        sim_printf("rtc->currd = %d\n", rtc->currd);
                    rtc->ticks = rtc->hz - 1;                     /* force clock calibration on next tick */
                    rtc->rtime = sim_throt_ms_start - 1000 + 1000/rtc->hz;/* adjust calibration parameters to reflect throttled rate */
                    rtc->gtime = sim_throt_inst_start - sim_throt_cps + sim_throt_cps/rtc->hz;
                    rtc->nxintv = 1000;
                    rtc->based = rtc->currd;
                    if (rtc->clock_unit) 
                        sim_activate_abs (rtc->clock_unit, rtc->currd);/* reschedule next tick */
                    }
                   SHOW_QUEUE();
                }
            }
```

I put `show_queue()` before and after the adjustment. This is before the adjustment:

```
Altair 8800 (Z80) event queue status, time = 305000700, executing 135,955,700 instructions/sec
SIMH at 4300 (32 usecs)
SOL20K at 28705 (211 usecs)
SOL20S at 111366 (819 usecs)
SOL20P at 111366 (819 usecs)
SOL20T at 329304 (2.422 msecs)
INT-CLOCK unit 8 at 1308457 (9.624 msecs) (Idle capable)
VDM1 at 1996664 (14.686 msecs)

Altair 8800 (Z80) #8 clock (INT-TIMER) co-schedule event queue status
INT-FLUSH on next tick plus 25980000 usecs
asynchronous pending event queue
Empty
asynch latency: 4000 nanoseconds
asynch instruction latency: 543 instructions
```

This is after the adjustment:

```
Altair 8800 (Z80) event queue status, time = 305000700, executing 210,000 instructions/sec
INT-TIMER at 2100 (10 msecs) (Idle capable)
SIMH at 4300 (20.476 msecs)
SOL20K at 28705 (136.69 msecs)
SOL20S at 111366 (530.314 msecs)
SOL20P at 111366 (530.314 msecs)
SOL20T at 329304 (1.568114 seconds)
VDM1 at 1996664 (9.507924 seconds)

Altair 8800 (Z80) #8 clock (INT-TIMER) co-schedule event queue status
INT-FLUSH on next tick plus 25980000 usecs
asynchronous pending event queue
Empty
asynch latency: 4000 nanoseconds
asynch instruction latency: 543 instructions
```

All of the service routines will be called later than they should. For example, the VDM1 service routine changes from 14.686 msecs to 9.5 seconds. This happens when the system changes from 135,000,000 instructions per second to 210,000 instructions per second. It seems the unit's wait times also need to be adjusted.

Again, the timers are beyond me, but when using "SET THROTTLE", the simulator's service routines experience a long delay when the throttle calibrates itself.

**Comment by markpizz** [comment]
Throttling was absolutely NEVER designed or intended to adjust unit wait times.

You started this since you're trying to get blinking cursor in your VDM1 device operating in the AltairZ80 simulator.

Some relevant history is related to the behavior you're seeing:

A long time ago, the AltairZ80 simulator invented its own solution to sucking down 100% of a host CPU core (this was likely when most systems only had 1 or at most 2 cores).  In general this concept (from SCP’s point of view) is called either IDLING or THROTTLING.  Idling is something that the simulator determines as needed and calls sim_idle() when it things it is merely waiting for some external activity.  Throttling doesn't involve anything specific in simulator code to achieve throttling.   Simulator execution merely sleeps some computed amount periodically attempting to achieve the specified throttle rate.  The AltairZ80 simulator solved the general problem by coding explicit calls to some sort of sleep in various parts of the simulator specific code.  This is NOT an OK paradigm according to many assumptions made in the SCP layer about timing and explicitly assumptions within the sim_timer library.  Since this was done long before there was support for IDLING and THROTTLING in SCP, the original internal mechanisms are still there.  Simulators which came up with their own solutions to general capabilities that SCP eventually added are implicitly grandfathered in to allowing their original solution to continue to exist, but the simulator also is then responsible for how it works (or doesn’t work) when actual IDLING or THROTTLING mechanisms are engaged.

I once looked at what it might take to remove the original sleeps in the AltairZ80, but it seemed that this stuff was scattered in may places and converting to the SCP facilities would be a significant project that was not a couple of lines of code change that would be the most I would ever do to a simulator I didn’t use all the time.  Such a conversion would  have to be something the primary owner of the simulator and its other contributors would have to undertake if they actually were interested.

Given the above, your VDM1 device is using a sim_activate_after() API to schedule device activations.  This API absolutely depends on a correctly calibrated clock (either a simulator provided one, or an internal one depending on if a simulator calibrates one),  With active calls to some sort of sleep in simulator code, correct meaningful calibration is impossible and thus sim_activate_after() should not be used.  Use sim_activate() with a constant wait value initially.  Once you're happy with that approach, you might want to somehow dynamically adjust the value that's used.

Once again, THROTTLING does NOT change and was never designed to change event wait times for any units.

**Comment by deltecent** [comment]
>The AltairZ80 simulator solved the general problem by coding explicit calls to some sort of sleep in various parts of the simulator specific code.

AltairZ80 simulator calls sleep in exactly 2 places:

1. In the CPU device if `clockFrequency` is set (defaults to 0).
2. In the SIO device if the device is being used and `SLEEP` is set (can be disabled with SET SIO NOSLEEP).

Neither is the case here. There are no rogue sleeps being called when using AltairZ80 with the SOL20 and VDM1 devices. The problem I am observing is when THROTTLE transitions from `SIM_THROT_STATE_TIME` to `SIM_THROT_STATE_THROTTLE`.

The comment for `sim_activate_after` reads:

```
/* sim_activate_after - activate (queue) event

   Inputs:
        uptr    =       pointer to unit
        usec_delay =    relative timeout (in microseconds)
   Outputs:
        reason  =       result (SCPE_OK if ok)
*/ 
    
t_stat sim_activate_after_abs (UNIT *uptr, uint32 usec_delay)
```

The second parameter is specified as being "microseconds" which is very specific and should be constant (other timer functions use "interval" which seems quite subjective). It is reasonable to expect that because "throttling doesn't involve anything specific in simulator code to achieve throttling", when the throttling mechanism changes internal timers, it would also make sure that events still activate in the amount of "microseconds" the simulator requested, not change 25000us to 9s, as the simulator has no idea this change is even taking place, has no mechanism to avoid it, and has no idea a constant unit of time can be stretched. The simulator is just wondering why its 25000us timer suddenly turned into 9s and then back to 25000us again.

I'm not asking THROTTLE to "change event wait times for any units". I'm thinking THROTTLE shouldn't change what a usec is as units of time are constant. Simulators have a reasonable expectation that a usec is a usec and won't change, especially when "throttling doesn't involve anything specific in simulator code to achieve throttling."

I do recall you mentioning something about `sim_clock_precalibrate_commands` that I tried to implement before but you didn't like my choice of "a bunch of simulator provided instructions that don't do anything", which is pretty much the definition of the NOP instruction. As it turns out, they need to do something specific in order to meet some undocumented requirement. That PR was scratched because the criteria was unknowable.

Is `sim_clock_precalibrate_commands` the (doesn't involve anything specific) simulator code that's required in order to have a simulator's events get dispatched in the requested amount of usecs during the first 10 seconds of execution when using throttling?

The throttling mechanism works great. The Sol-20 has many games that require timing. Air Traffic Controller updates aircraft every 15 seconds. With SCP handling the throttling, the game play seems very accurate (after the first ~10 seconds of game play). I also think the Sol-20 is a relevant piece of history and would be a nice addition to AltairZ80.

In addition to the blinking cursor, events are being used to perform video refresh, and keyboard, tape, serial, and parallel I/O. The real Sol-20 didn't have a 9 second video and I/O delay 2 seconds after boot. That's what I'm trying to avoid.

**Comment by deltecent** [comment]
```
static const char *cpu_8080_clock_precalibrate_commands[] = {
    "-m 100 LXI H,200H",                            
    "-m 103 MVI B,0",                               
    "-m 105 DCR B",
    "-m 106 MOV M,B",                               
    "-m 107 INX H",
    "-m 108 JNZ 0105H",                             
    "-m 10B JMP 0100H",                             
    "DEP PC 100",
    NULL};
```

This seems to correct the usec time continuum stretching. I just need 8080 instructions that will be permitted to make it into the AltairZ80 simulator.

**Comment by markpizz** [comment]
> The second parameter is specified as being "microseconds" which is very specific and should be constant (other timer functions use "interval" which seems quite subjective). It is reasonable to expect that because "throttling doesn't involve anything specific in simulator code to achieve throttling", when the throttling mechanism changes internal timers, it would also make sure that events still activate in the amount of "microseconds" the simulator requested, not change 25000us to 9s, as the simulator has no idea this change is even taking place, has no mechanism to avoid it, and has no idea a constant unit of time can be stretched. The simulator is just wondering why its 25000us timer suddenly turned into 9s and then back to 25000us again.
> 
> I'm not asking THROTTLE to "change event wait times for any units". I'm thinking THROTTLE shouldn't change what a usec is as units of time are constant. Simulators have a reasonable expectation that a usec is a usec and won't change, especially when "throttling doesn't involve anything specific in simulator code to achieve throttling."

The host systems which simh runs on, DO NOT have a way of actually delaying for some number of usecs .  Therefore usec delays are determined on the fly by tracking instruction execution which on most (if not all modern hosts), actually usually happen a good number of times per usec.  The instruction execution rate is observed during clock calibration for clock ticks and execution rate can change somewhat significantly based on various things going on in the host system (i.e. other processes competing for the CPU, processor dynamic changes to host cpu execution - SpeedStep, etc.).  Given this, the simulator instruction execution rate is continuously observed and updated 
periodically.  The resulting updates then are used to determine usec delays. Any calls to sleep() by simulator execution in sim_instr)_ will play havoc with the accuracy of the calibration process and thus make usec delays used in sim_activate_after() and sim_activated_after_abs() particularly inaccurate.

> static const char *cpu_8080_clock_precalibrate_commands[] = {
> ...
>
> This seems to correct the usec time continuum stretching. I just need 8080 instructions that will be permitted to make it into the AltairZ80 simulator.

The clock pre-calibration is done before the simulator makes it to the first "sim> " prompt.  Pre-calibration for the AltairZ80 simulator must therefore use instructions that the simulator initially starts up with.  Surely, with this simulator you can change the CPU type and thus the instruction set that may be usable after such a change, but the pre-calibrated value will still be a better guess as a starting point for a calibrated execution rate on the host computer than the arbitrary fixed value that is used when you don't pre-calibrate.

I'm glad that this will work for you given the specific setup you've got that you say avoids the sleeps done in the simulator code at this time.  

Once again, if the simulator code (invoked from within sim_instr()) calls any sleep routines, the delay values specified in the sim_activate_after() and sim_activate_after_abs() APIs will never be correct but in your case they may be "good enough" for what you are doing.
