### ISSUE TITLE
Setup Coverity Scan

### ISSUE THREAD

**Issue by XVilka** [open-simh/simh#234]
[Coverity Scan](https://scan.coverity.com/) offers free access for open source projects, and is one of the best static analysis tools in the world. Adopted by many big projects like Linux kernel, it has proven it's usefulness for more than a decade. Setting it up for SIMH would help to fish out for obvious bugs that weren't noticed during the development.

## Build Limits
The number of weekly builds per project are as follows:

- Up to 28 builds per week, with a maximum of 4 builds per day, for projects with fewer than 100K lines of code
- Up to 21 builds per week, with a maximum of 3 builds per day, for projects with 100K to 500K lines of code
- Up to 14 builds per week, with a maximum of 2 build per day, for projects with 500K to 1 million lines of code
- Up to 7 builds per week, with a maximum of 1 build per day, for projects with more than 1 million lines of code

**Comment by markpizz** [comment]
Good idea.  

It's been quite a while since coverity scans have been run on simh source.

If you want to own the Coverity testing as was done previously that would be fine, or if you want to enrich the CI/CD code to run things automatically that would be great.

I might have write access to the existing Coverity simh project and if I do, I'd be glad to grant you the same.  Please let me know how to check...
