### ISSUE TITLE
SCP: Debug to STDOUT produces "staircase" output

### ISSUE THREAD

**Issue by al20878** [open-simh/simh#250]
- #### Context
```
sim> set debug stdout
sim> set rc debug
```
when DOS/BATCH runs, I see the following debugging output:

```
>>RC wr: RCDA 000001, PC 015372
                               >>RC rd: RCDA 000001, PC 015374
                                                              >>RC wr: RCDA 000002, PC 015374
                                                                                             >>RC wr: RCCA 060324
                                                                                                                 >>RC wr: RCWC 177700, PC 015404
            >>RC start: cs = 105, da = 2, ma = 60324, wc = 177700
                                                                 >>RC done: cs = 305, da = 4, ma = 60524, wc = 0
                                                                                                                >>RC rd: RCER 000000
                                                                                                                                   >>RC rd: RCCS 000304
                   >>RC wr: RCDA 000000, PC 015372
                                                  >>RC rd: RCDA 000000, PC 015374
                                                                                 >>RC wr: RCDA 000000, PC 015374
                                                                                                                >>RC wr: RCCA 060324
                                                                                                                                   >>RC wr: RCWC 177700, PC 015404
                              >>RC start: cs = 105, da = 0, ma = 60324, wc = 177700
                                                                                   >>RC done: cs = 305, da = 2, ma = 60524, wc = 0
                                                                                                                                  >>RC rd: RCER 000000
                  >>RC rd: RCCS 000304
```
Rather hard to read.  Why is it stair-cased?
- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue
fresh build from github
- #### how you built the simulator or that you're using prebuilt binaries

make pdp11 DEBUG=1 NOVIDEO=1 NONETWORK=1
- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

See above
When I sent output to the file with `set debug file`, it was produced there correctly:
```
sim> b rk
>>RC rd: RCDA 000000, PC 010724
>>RC wr: RCDA 000001, PC 015372
>>RC rd: RCDA 000001, PC 015374
>>RC wr: RCDA 000002, PC 015374
>>RC wr: RCCA 060324
>>RC wr: RCWC 177700, PC 015404
>>RC start: cs = 105, da = 2, ma = 60324, wc = 177700
>>RC done: cs = 305, da = 4, ma = 60524, wc = 0
>>RC rd: RCER 000000
>>RC rd: RCCS 000304
>>RC wr: RCDA 000000, PC 015372
>>RC rd: RCDA 000000, PC 015374
>>RC wr: RCDA 000000, PC 015374
>>RC wr: RCCA 060324
>>RC wr: RCWC 177700, PC 015404
>>RC start: cs = 105, da = 0, ma = 60324, wc = 177700
>>RC done: cs = 305, da = 2, ma = 60524, wc = 0
>>RC rd: RCER 000000
>>RC rd: RCCS 000304
>>RF start: cs = 104, da = 100, ma = 60324
>>RF done: cs = 304, dae = 0, da = 200, ma = 60524, wc = 0
>>RF start: cs = 104, da = 671600, ma = 342
>>RF done: cs = 140304, dae = 2000, da = 161417, ma = 160000, wc = 76535
```
This is the expected behavior in console just as well, IMO.
- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Please notice this in sim_defs.h:
```
/* Deprecated Debug macros.  Use sim_debug() */

#define DEBUG_PRS(d)    (sim_deb && d.dctrl)
#define DEBUG_PRD(d)    (sim_deb && d->dctrl)
#define DEBUG_PRI(d,m)  (sim_deb && (d.dctrl & (m)))
#define DEBUG_PRJ(d,m)  (sim_deb && ((d)->dctrl & (m)))
```
Notice for example, the code in pdp11_rc.c:
```
            if (DEBUG_PRS (rc_dev))
                fprintf (sim_deb, ">>RC rd: RCDA %06o, PC %06o\n",
                         rc_da, PC);
```

When the simulator is running, STDOUT to a terminal device is set to the logical equivalent of raw mode which emits all bytes emitted precisely as the bytes themselves without any translation of newlines (LF) to CRLF which is normally done when you examine a file while not in raw mode.  So the simple fprintf in these debug messages is doing precisely as expected.

If, as  mentioned in the sim_defs.h comments about the deprecated macros, sim_debug was used to emit the desired output, rather than merely a simple fprintf, different results would be observed AND the additional feature information provided by sim_debug would also be available.

It is strongly advised that newly written simulator device code use sim_debug.  

You've notice that the debug being output to a file and then examined later would be the preferred debug procedure when dealing with debugging simulator code that uses these deprecated debug paradigm macros.

**Comment by al20878** [comment]
Okay, so it's a feature.  I wonder should it be correct to just replace \n with \r\n in those old fprintf statements?

**Comment by markpizz** [comment]
Most people have no need to run with debugging enabled, and even then essentially never need to debug directly to STDOUT for devices that have been stable essentially forever.   

If you're doing this since you've detected some functional problem with an existing device, point that out the author of a module that uses the legacy debug macros, you shuold work with them on changes.  If you're writing new device code (your recent RR device PR), then you should NOT be using the ancient (deprecated) debugging methodology.  Like sim_defs.h says, use sim_debug.

**Comment by al20878** [comment]
I used the "NT" ("New Technology" LOL) debugging calls in my code.  What I was trying to do with this one, was to get an ancient DOS going, unrelated to the RR/RP thing.  I was so far unsuccessful with that version of the OS, and had to resort to debugging to see what was going on with the devices, hence, the output to stdout.

**Comment by pkoning2** [comment]
> Okay, so it's a feature. I wonder should it be correct to just replace \n with \r\n in those old fprintf statements?

Mark described the preferred fix, which is to use `sim_debug`.  And no, this is a bug, not a feature.

**Comment by markpizz** [comment]
If you're going to consider it a bug and suggest changing \n to \r\n, then essentially ALL of Bob's devices use the legacy debugging macros and write directly to sim_debug with fprintf.  There are MANY devices which which then have the same bug.  

Bob managed to get as far as he did without using STDOUT as a debug destination.    He's fine with owning problems with all of his authored devices and it should be up to him to assess if it is a bug.

**Comment by al20878** [comment]
Ok, since you have reopened this, I just want to let you know that the same thing happens with debugging of the TC and RF devices -- since I was using those as well in my DOS/Batch experiments.

**Comment by pkoning2** [comment]
Ok, so I thought this was an isolated problem.  Never mind then.  I guess the workaround is "send debug output to a file".
