### ISSUE TITLE
Windows XP toolkit install incomplete (again) on GH CI/CD

### ISSUE THREAD

**Issue by bscottm** [open-simh/simh#261]
Issue title should be self-explanitory. Spent the last week frobbing command line flags to figure out what's missing or needed to ensure a complete 'v141_xp' toolkit install in the existing Visual Studio Enterprise installation on Github's CI/CD pipeline. The seemingly important command line flags are `--norestart` and `--force`.

Honestly, this is playing whack-a-mole with Microsoft's VS installer. I think I've got it stable (again), until the next time it fails for some hard to diagnose reason.

PR #260 has the latest fixes that hopefully resolves this recurring issue for a while.

CC: @sethm @Xvilka

**Comment by bscottm** [comment]
I often wonder whether maintaining XP compatibility "juice" is worth the "squeeze". SIMH needs to maintain a Windows build, but given that XP is beyond obsolete as an operating system and the last release for the XP development kit is verging on, if not over, 6 years ago.

Contrary to popular abuse, this isn't a cmake-specific issue. It's a matter of installing the XP development kit as an add-on to the existing compiler suite. CMake avoids some of the issues in a previous Windows-build issue by building the dependency libraries during each build.

It's hard to build those libraries if the development kit isn't installed -- any build system will be plagued by this issue.

**Comment by markpizz** [comment]
Using the term XP explicitly obscures the fact that XP functionality includes EVERY release since XP.  When you keep on referring to this long obsolete OS version as all that matters, you're ignoring:  Windows Vista, Windows 7, Windows 8, Windows 8.1, Windows 10 and Windows 11, along with the related servers.  Surely some of these are also obsolete, but there are still systems in the field.  Which of these does a VS2022 built binary just run on?

**Comment by bscottm** [comment]
@markpizz: Windows 10 and 11 are the general targets of VS 2022 SDKs. The fact that I have to jump through all kinds of hoops and arcana to install the **_XP SDK_** is a strong argument for **_NOT_** supporting it. Granted, there's bugwards compatibility forward from WinXP to Windows 11, but that's just building for the least common denominator and an artifact of how MS built the Windows API with a lot of ordinal symbols in the runtime DLLs.

Sometimes coding for the least common denominator is a good thing. I don't think it's applicable here the whack-a-mole tournament involved with installing the SDK.

No, I never tried running a VS 2022 binary on a XP system because (a) I don't have an XP-based VM, (b) it's a counterproductive use of my time.

**Comment by markpizz** [comment]
Rather than chasing Microsoft's continuous changing of the VMs running the CI activities maybe it would be useful to somehow keep a snapshot of an environment that works and doesn't change behind your back.  Use that unchanging environment for your CI builds until there's a practical need to change things.

It seems that you have the most expertise working with the github actions environment, maybe there's another way to skin this cat.  The tools and libraries needed to perform the simh CI activities don't need to change very often and everything certainly needn't be reinstalled and rebuilt each time there's a commit or a PR merge.  Since you're building binaries that are linked statically, there should be no external dependencies on the systems that these binaries will be run on.  The point of the CI activities is to build and test the simh source.  It really isn't to build and run the whole toolchain each time.

**Comment by bscottm** [comment]
Sure, I could cache the libraries and end up with the other previous Windows Build problem you encountered. Pick your poison.

**Comment by markpizz** [comment]
I really wasn't primarily referring to the libraries but mostly the pieces of the compiler install.  If the CI build is actually building the XP targets, then the windows-build compiler problem would never happen.  It only happens when Microsoft releases and intermediate 'current' compiler and you then try to build without targeting the XP binaries.  It seems that they make such a release approximately every 6 months during a particular VS lifecycle.  If the compiler were able to be unchanging, then there wouldn't be any changes needed to libraries.

**Comment by pkoning2** [comment]
Re snapshot: that's what I was wondering about too.  Or to put it differently: why did the tools change in the first place?  I fully agree that they shouldn't unless we want them to and we'd only want that if there is a really good reason.  The fact that a newer version might be available is utterly irrelevant.

So we're back to that question: once we figured out how to recover from the current mess, how to we freeze things so this doesn't happen in the future?  Since I don't know how the CI stuff works I have no idea how to answer that question.

**Comment by markpizz** [comment]
From the not a crazy amount of digging, I did, it seems that the github system snapshots change periodically all by themselves with everything they contain.  It doesn't seem possible to hang on to one which works for you.  I suspect that some of this relates to the magic and automatic interfaces to the various features that github provides.  It would seem to me that the interfacing magic could have been setup as an extra drive on the VM setups, but it doesn't look like that's what they did.

Github actions aren't the only CI alternative.  Lars had originally setup CI to do Windows builds using Appveyor (which has a VS2008 build environment that will build the original VS projects directly).  He had travis setup for the non Windows platforms.  I'm not sure why he went for travis.  Maybe the resource consumption limits on the Appveyor free service was too much...
Appveyor absolutely allows custom build images: https://www.appveyor.com/docs/custom-build-images/
Maybe github actions could take advantage of Docker images to help with this, but I know nothing about any of that.

**Comment by XVilka** [comment]
We have positive experience with AppVeyor but with paid account. They do still update their standard Windows images, just not quite as often as GitHub.

**Comment by pkoning2** [comment]
The PR is merged and it appears to cure the issue.  Much appreciated!
