### ISSUE TITLE
SIMH prevents screensaver/sleep on Mac OS

### ISSUE THREAD

**Issue by louis-chretien** [open-simh/simh#38]
I recently noticed that SIMH seems to prevent Mac Os from activating the screen saver and/or sleeping the display after the number of minutes set in System Preferences.

When i ran Activity Monitor on the machine, i saw that the SIMH process was using 100% of 1 CPU.

When i used "set cpu idle", i saw that number drop quite a bit, to around 15% of 1 CPU.

But the screensaver still didn't kick in.

Im curious to know if that is a "bug" in the implementation on Mac OS, or if other versions (Windows/Linux) experience the same thing?

**Comment by pkoning2** [comment]
The lack of screensaver is a side effect of the 100% CPU.  That's normal unless  (a) you've set "idle" and (b) the OS you're running supports that.  For example, on PDP-11, you can set idle, but it doesn't work for RT-11 SJ.  It does work for RSTS, and others.  On VAX, if I remember right, there are several idle options where you tell it the OS you're using, since there is no standard hardware idle mechanism as there is on the PDP-11, so the simulator looks for known idle schemes for various OS.

**Comment by pkoning2** [comment]
That's worth investigating.   If that's the reason, it's clearly a bug, either in our usage of SDL, or in SDL itself.  It is obviously wrong for "video" stuff to disable the screen saver, unless specifically requested by user via preference settings and then only if such a thing makes sense at all (which is very unlikely).

**Comment by louis-chretien** [comment]
For what it's worth, the simulators i was using were pdp11 and vax.

I had pdp11 running with RSTS/E 10.1-L, and vax running OpenVMS Hobbyist 7.3

**Comment by markpizz** [comment]
This behavior started with relatively recent versions of SDL with no changes in the simulator device code, and no change in sim_video either.  Simulators that have a video capable device run the simulator main thread (in scp c) in a separate thread since on some platforms (MacOS in particular), keyboard and mouse events are only delivered to the primary/original process thread.

These simulators always run the scp main in a new thread with minimal/no SDL setup until a device presents a display(aka window).

**Comment by pkoning2** [comment]
I remember that "main thread" stuff.  But doesn't this simply mean that the main thread should start the SCP thread, and then wait to see if anyone actually wants to activate the SDL machinery?  If SDL isn't called at all (not even to initialize it) this problem should presumably go away, right?
Meanwhile, it would make sense to look at SDL to see why they introduced this defect, and if they can be induced to fix it.  As I said, the mere fact you turned on a video service has nothing to do with screen savers, so this change looks like a bug to me.

**Comment by pkoning2** [comment]
Should now be fixed.
