### ISSUE TITLE
pdp10 emeulator crashing after tops10 decnet compile

### ISSUE THREAD

**Issue by drforbin** [open-simh/simh#405]
I'm running pdp10 ks 10 emulator.. I recently compiled no errors a decnet monitor.
This is what I'm getting when trying to boot.

any ideas would be great appreciated! 

Startup option: go
[Rebuilding the system search list from the HOMe blocks]

[Rebuilding the active swapping list from the HOMe blocks]

[Rebuilding the system dump list from the HOMe blocks]

?Stopcode DMO, type=STOP, on CPU0 at 1-Dec-115 59.15

CPU Status Block

APRID = 470130,,010001
CONI APR, = 000000,,000020
CONI PI, = 000000,,000220
CONI PAG, = 000000,,060000
DATAI PAG, = 500100,,000003
Reload monitor
BOOT>qi\iq\
BOOT>
[Loading from DSKB:SYSNET.EXE[1,4]]
^O

- #### Context

- #### the output of "sim> SHOW VERSION" while running the simulator which is having the issue

- #### how you built the simulator or that you're using prebuilt binaries

- #### the simulator configuration file (or commands) which were used when the problem occurred.

- #### the expected behavior and the actual behavior

- #### you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Hi @drforbin,

If, when you created this issue, you actually provided ALL of the information mentioned in the issue template, no one would have to ask you to provide all the requested details so that they could begin to help you.

- Context
- the output of "sim> SHOW VERSION" while running the simulator which is having the issue
- how you built the simulator or that you're using prebuilt binaries
- the simulator configuration file (or commands) which were used when the problem occurred.
- the expected behavior and the actual behavior
- you may also need to provide specific pointers to data files that may be necessary to demonstrate the problem

**Comment by markpizz** [comment]
Lacking the requested details, the @drforbin should provide some or this issue should be closed.

**Comment by drforbin** [comment]
Hey guys...I'm sorry. the crash had nothing to do with simh. It was the dec monitor not loading at the right address.

**Comment by pkoning2** [comment]
Your title was that the emulator crashed.  Did it really, or did the PDP-10 code running inside the emulator crash?
If you load something at the wrong address, it makes sense that the emulated program would crash.  But that wouldn't explain, or justify, a crash of the emulator itself.
Please confirm what you meant.  If it was a pdp-10 program crash, this issue should be closed.  If it was an emulator crash, you need to supply all the details and leave this open.

**Comment by drforbin** [comment]
The point I'm making is the emulator was not to blame. SIMH is fine.

**Comment by pkoning2** [comment]
Thanks.  It helps if the title of the issue accurately summarizes what went wrong.

**Comment by drforbin** [comment]
What you like me to give more of an explanation ?

**Comment by pkoning2** [comment]
No, I got it.  What I meant is that the summary should not say "the emulator crashed" if the emulator didn't crash.
