### ISSUE TITLE
Modernize and simplify the building system

### ISSUE THREAD

**Issue by XVilka** [open-simh/simh#7]
There were multiple suggestions to switch to the higher-level buildsystem for SIMH to simplify the readability, portability, and structure of the project. Two main options were offered - CMake and Meson.

# CMake

@bscottm ported the SIMH to the CMake here: https://github.com/simh/simh/pull/775

> Add CMake build support as a parallel alternative to the makefile-based build system. This is not intended to be a replacement for the makefile-based build system (or the collection of Visual Studio solutions, for that matter.)
> 
> CMake is a meta-build system: It generates the build environment for a multiplicity of build systems (Ninja, VS 2019, VS 2015, MinGW Makefiles, to name a few). Documentation for how to use is in README-cmake.md.

# Meson

To simplify compilation and cross-platform support, and inspired by various C projects that switched from Autotools to Meson, including QEMU, I did an initial work of migrating from the Makefile to Meson.

There are two implementations of this language:
- [Meson](https://mesonbuild.com)
- [Muon](https://sr.ht/~lattis/muon/) - mostly work-in-progress

For now, I did the simplest compilation without running tests and optional features. Please let me know if there is an interest in this, before I proceed.

I split into two commits - adding the buildsystem and removing the unnecessary files.
The second commit is not really necessary, since these can coexist without any conflict, making the gradual transition possible, like X.org, Wayland, Mesa, QEMU did, slowly deprecating autotools on the course of multiple releases.

My PR was https://github.com/simh/simh/pull/1099 - less complete than the CMake one, I think.

**Comment by LegalizeAdulthood** [comment]
CMake is what the entire C/C++ community has been moving towards for years.  CMake is mature, battle tested and has a huge community of users that can help you if you need it.

As a long-time C/C++ developer I have to say that I've never even heard of Meson/Muon.  Lately (last ~5 yrs or so) a bunch of new build systems have been popping up in the C/C++ community and none of them are sufficiently better than CMake to warrant the community's interest.  Looking up Meson, wikipedia says it's been around for 9 years.  That I've never heard of it (and I'm a bit of a C/C++ geek) implies it doesn't have any significant mindshare in the C/C++ community.

**Comment by eli-schwartz** [comment]
> none of them are sufficiently better than CMake to warrant the community's interest. Looking up Meson, wikipedia says it's been around for 9 years. That I've never heard of it (and I'm a bit of a C/C++ geek) implies it doesn't have any significant mindshare in the C/C++ community.

https://en.wikipedia.org/wiki/Argumentum_ad_populum

There are some fairly significant differences though -- for example, cmake is the POSIX shell of build systems, it has no datatypes, not even lists, so the convention is to use `;`-delimited strings instead. Even GNU bash recognized the tremendous importance of a real, first-class array type. Meson has first-class arrays, strings, integers, booleans, and more specialized objects with specialized methods. It makes it siginificantly harder to make a whole class of mistakes...

...

None of this actually seems to matter since this project is so diametrically opposed to switching build systems that attempting to propose either cmake or Meson apparently results in hostility and either closing the proposal or intimidating the submitter into retracting it, which is certainly... ***a*** thing.

And yes, either build system would represent an upgrade from raw Makefiles that only support GNU make and in the process contain half a build system's worth of primitive functions such as `find_library` (cmake/meson) and `has_header` (meson) / `check_include_file` (cmake) implementations as GNU make functions.

**Comment by LegalizeAdulthood** [comment]
LOL

**Comment by pkoning2** [comment]
Eli, I know a little about CMake, a little about configure (enough to want to avoid it if I can) and nothing at all about any of the other systems mentioned.

But that doesn't matter.  If I were to undertake a revision of the build machinery I'd probably pick CMake.  I mentioned it because I spent half an hour playing with it, and because I've seen a much more substantial beginning of such work by others.  However, if you want to do a build system with some other tool, we'd definitely entertain it.  Just make sure it supports the platforms that SIMH currently works with.

As for "hostility" and "closing the proposal", I have no idea what you're talking about.  If you take a look at the project principles for Open SIMH that we articulated when we created the project, you should, I believe, see that we welcome all helpful contributions.  We have a build system today that works, after a fashion, but it has a pile of problems and is hard to maintain.  And it doesn't support Windows (that is done by an entirely unrelated setup).  So clearly there is opportunity for improvement, and clearly interest has been expressed in it.

As with other open source projects, doing the work is what really makes things happen.  Arguing about theory is ok at the start of a significant effort, but it isn't sufficient to deliver anything.  If there are two proposed directions but only one of them is actually implemented, that's the one that will go forward -- assuming it doesn't have unacceptable flaws.

**Comment by XVilka** [comment]
I can help with updating, and improving either of those.

**Comment by pkoning2** [comment]
Please note: right now we have nothing other than some discussion.  I'd suggest the creation of a complete implementation, not just skeletons.  (We have skeletons, but those are not ready to become replacement build systems.)  It doesn't need to do more than the current Makefile, though more (such as packaging) has been suggested and would be valuable.  But it shouldn't do less, and it should be shown to work on at least the major platforms (Linux, various BSDs, Mac, Windows).  And it should handle, cleanly, the optional libraries that a number of the emulators can use -- that in fact is one of the problem areas in the existing system.

**Comment by LegalizeAdulthood** [comment]
I contributed a [pull request](https://github.com/retroprom/simh/pull/1) for the existing CMake work in [retroprom's fork](https://github.com/retroprom/simh) that has everything building on Windows.  It hasn't been accepted yet there, however.

**Comment by eschaton** [comment]
One of the things I’ve heard cited occasionally about SIMH’s build system is that it intentionally passes all source files to the compiler at once for a given binary “to improve optimization.”

This may be the intent, but C’s compilation model doesn’t actually support it: Each source file must still be treated by the compiler as an independent compilation unit without reference to the others. A sufficiently smart compiler may do things like make copy-on-write copies of cached preprocessed contents of header files to reuse between compilation units, but I don’t know of any compilers that actually do this, instead relying on user & build system direction such as the creation of precompiled prefix files passed to each compilation.

SIMH build performance would be much better served—even without changing to another build system—by simply switching to separate compilation of all source files, and perhaps building static or dynamic libraries for the shared content. That way such content only needs to be built a small number of times even when building all simulators, and any changes to a file in the shared content only require recompiling one file a couple times and linking a couple of libraries.

In my own builds using Xcode I set up `libsimhA32I32` and `libsimhA64I64` targets—to distinguish using 32-bit versus 64-bit values for simulated addresses and integers—and not only has doing so worked out great, the build is also _incredibly_ fast compared to the makefile, especially when changing things.

**Comment by pkoning2** [comment]
Does the common code indeed narrow down to just two cases, 32 bit vs. 64 bit?  It would be nice if that's good enough.
As for the compilation model, you're right, and the slowness of passing everything to a single compile even if only one or two files have changed is annoying.  
Recent versions of GCC support "link time optimization", which I think can do certain types of global (across source files) optimization, but I've never dug into the details.   The current code uses LTO, judging by various messages, and that slows things down a lot more still.  I wonder how much difference it makes.  It would be good to compare plain old conventional -O2 vs. -O3  vs. -O3 with LTO vs. all that with profiling, and document the result for one or two selected simulators.

**Comment by Rhialto** [comment]
There is, however, "Link Time Optimization", or LTO. Both clang and gcc
support it. You can find some options referencing LTO in the Makefile.

One way in which it works is that the object files contain not only the
assembled machine code, but also some intermediate representation of
the compilation module. The linker can then look at that and re-generate
code, based on the whole program.

I think that in the current makefile, this is turned off for the general
case.  In the packaging done in pkgsrc, it has historically been forced
off in any case.  Presumably because there were reliability problems
with it.

-Olaf.
-- 
___ "Buying carbon credits is a bit like a serial killer paying someone else to
\X/  have kids to make his activity cost neutral." -The BOFH    ***@***.***

**Comment by pkoning2** [comment]
When I build on my Mac I see LTO messages, so if it's meant to be turned off, that doesn't seem to be happening at least with CLang (M1, i.e., ARM64, target).

**Comment by Rhialto** [comment]
Do note that it may be not 100% trivial to share object files between
emulators, even if they are built from the same source file. There may
be #defines that make them different (such as -DVAX_47 or
-D-DUSE_SIM_VIDEO).

**Comment by eschaton** [comment]
Both LLVM and GNU tool chains support some form of LTO but that’s generally applied at link time. It does slow down the Xcode build to enable LTO; it goes from 22 seconds to 37 seconds for an optimized build, which is still way faster than the 120 seconds the makefile takes.

As for sharing of object files between builds, what I found via source inspection a couple years back was that the shared support code (`sim_*.[ch]`) has almost nothing that needs to differ between _simulators_ but only stuff that needs to vary based on 32/64-bit address and integer, how you’ve selected to do networking, whether to support video, etc. When last I looked it was actually pretty nicely separated from the simulators themselves.

**Comment by Rhialto** [comment]
The makefile is rather convoluted...       
                                           
When I last looked, for Darwin, LTO seems explicitly turned on.
                                                                   
For some (many/all?) other cases, there is a `NO_LTO = 1` both in the
then-part and the else-part of a condition (around line 1210). Then
there is a variable `LTO_EXCLUDE_VERSIONS` which also causes `NO_LTO = 1`.
And around line 520 there is a test which checks if gcc seems to support
LTO, and disables it if it seems not.      
                                             
In any case, if I compile with the makefile from the repo (and not
edited as by pkgsrc), I see no signs of LTO. That's on NetBSD/amd64 with
gcc 7 or 8.

**Comment by LegalizeAdulthood** [comment]
In the CMake pull request, all source files are first compiled to object files and then linked.  Enabling LTO can be supported, although I haven't done anything specific for that yet (it's just managing compiler and linker flags).  I initially attempted to compile the `sim_*.c` files just once and then share them across all simulators until I realized that there were some features that were flipped by macros and would leak throughout the code.  So, I reverted back to the makefile's behavior of re-compiling the `sim_*.c` files for every simulator.  My impression is that there are two flavors: 32-bit and 64-bit, plus optionally enabling the card reader support.  However, I haven't exhaustively examined the code to verify this.  If there are only a handful of variants used by the simulators, then extracting each variant as a library and having each simulator connected to the proper variant should cut down on build times for everything.  Certainly the existing makefile causes a recompile of *every* source file whenever you touch *any* source or header file.  This is obviously less than desirable for active development of any simulator, but it's fine if your use case is "build and run" and not "edit, compile, test".

**Comment by bscottm** [comment]
First off, I'm really happy to see the discussion. Proposing anything to `simh` results in a very high degree of skepticism that is hard to overcome. It's not nasty; it's "Well, we didn't invent it, so why should we adopt it?" Taking advantage of 0/1 as boolean expression values in computing VAX condition codes was another fun interchange with the `simh` developers... a feature that's been part of C since C99... but I digress...

When I "ported" the `simh` build system to CMake, I had the following objectives: (a) generate the various `simh` library variants independently, (b) create a straightforward way to add/describe a simulator, (c) build the dependency libraries (SDL2, pcap, zlib, etc.) when needed (Windows, anyone?) and (d) make it easy to maintain. The CMake build system depends on a Python script to automagically generate the CMake simulators, which is a feature that the `simh` maintainers suggested (and it made the build system a bit more robust, to be honest.)

More recently, I've added the ability to use CTest to the build system. There aren't a lot of simulator tests needed ATM. It seems to me that the whole "testlib" command and its tests could be moved over to a CTest harness.

Re: Meson and Muon: I did consider these. I didn't see widespread adoption, which made the decision to use CMake a lot easier.

**Comment by bscottm** [comment]
> In the CMake pull request, all source files are first compiled to object files and then linked. Enabling LTO can be supported, although I haven't done anything specific for that yet (it's just managing compiler and linker flags). I initially attempted to compile the `sim_*.c` files just once and then share them across all simulators until I realized that there were some features that were flipped by macros and would leak throughout the code. So, I reverted back to the makefile's behavior of re-compiling the `sim_*.c` files for every simulator. My impression is that there are two flavors: 32-bit and 64-bit, plus optionally enabling the card reader support. However, I haven't exhaustively examined the code to verify this. If there are only a handful of variants used by the simulators, then extracting each variant as a library and having each simulator connected to the proper variant should cut down on build times for everything. Certainly the existing makefile causes a recompile of _every_ source file whenever you touch _any_ source or header file. This is obviously less than desirable for active development of any simulator, but it's fine if your use case is "build and run" and not "edit, compile, test".

That's exactly why the CMake build compiles a bunch of simh variant libraries -- there are 32 vs. 64-bit variants (internally, there's code that needs 64-bit integers/values, e.g., VAX) and others where 32-bit is sufficient (e.g., PDP-11, PDP-8.) And, yes, those macros do propagate down through the code, although, not necessarily into an actual simulator.

**Comment by bscottm** [comment]
FWIW: The relatively up-to-date [CMake-based simh](https://github.com/bscottm/simh-cmake) is available as one of my repos. :-)

There was a recent issue with OpenSSL compiles on more recent Visual Studio compilers (MS removed `off_t`), which I haven't followed up on or fixed. Otherwise, it should be fairly synchronized with simh/simh.

**Comment by bscottm** [comment]
> Does the common code indeed narrow down to just two cases, 32 bit vs. 64 bit? It would be nice if that's good enough. As for the compilation model, you're right, and the slowness of passing everything to a single compile even if only one or two files have changed is annoying. Recent versions of GCC support "link time optimization", which I think can do certain types of global (across source files) optimization, but I've never dug into the details. The current code uses LTO, judging by various messages, and that slows things down a lot more still. I wonder how much difference it makes. It would be good to compare plain old conventional -O2 vs. -O3 vs. -O3 with LTO vs. all that with profiling, and document the result for one or two selected simulators.

No, it doesn't narrow down to just 32 vs. 64-bit. There are video and network variants as well. IIRC, about 6 library variants.

**Comment by bscottm** [comment]
Also, DO NOT COMPILE WITH "-O3". There's a complete cleanup code hygiene pass needed that has to do with integer overflow (there's a GCC warning where these potentially occur). And it's not trivial.

There isn't a lot of consistency in the code with respect to signed/unsigned integer hygiene.

**Comment by LegalizeAdulthood** [comment]
> FWIW: The relatively up-to-date [CMake-based simh](https://github.com/bscottm/simh-cmake) is available as one of my repos. :-)
> 
> There was a recent issue with OpenSSL compiles on more recent Visual Studio compilers (MS removed `off_t`), which I haven't followed up on or fixed. Otherwise, it should be fairly synchronized with simh/simh. If you do compile on Windows, VS 2019 should still be good.

Why don't you make a pull request?

**Comment by bscottm** [comment]
> > FWIW: The relatively up-to-date [CMake-based simh](https://github.com/bscottm/simh-cmake) is available as one of my repos. :-)
> > There was a recent issue with OpenSSL compiles on more recent Visual Studio compilers (MS removed `off_t`), which I haven't followed up on or fixed. Otherwise, it should be fairly synchronized with simh/simh. If you do compile on Windows, VS 2019 should still be good.
> 
> Why don't you make a pull request?

To which repo? :-)

**Comment by LegalizeAdulthood** [comment]
This one; simh/simh is a dead end and that's why this repo exists in the first place.

**Comment by bscottm** [comment]
I'll take a look at what would be involved. There are likely more changes to my repo (e.g., VAX condition code alternative, sign extensions via casting) that you might not want, or might be hard to break apart.

**Comment by rcornwell** [comment]
I don't think the issue with switching to CMake is "Well, we didn't invent it, so why should we adopt it?", rather it is that the Makefile is pretty easy to add in new simulators. However the logic at the top of it is a nightmare. So I am all in favor of updating the build system to something more cross platform. Traditionally SimH supported VMS, Unix and Windows, and compatibly was important. Many simulators have various flags that are added to the builds to include/exclude specific features. I am not sure how a common library will work. Which leads to one of the biggest issues with global changes to simh. And that is testing.

There is no simulator specific testing cases to validate whether a simulator compiles or not. Mark added the ability to run a set of scripts to do basic validation of some simulators. However this is far from complete. I know that it takes me about 12 hours to run all the test cases for my simulators. And I have found from experience that making a simple change in one file can fix things for one operating system, and break several others. Even though the system passes diagnostics.

Add CTEST might be useful, however the testcases have to be written. And this might not be as simple as it sounds.

**Comment by pkoning2** [comment]
Re "do not compile with -O3", I think the better answer is to include one of the -fsomething flags that tells the compiler not to optimize on the assumption that signed overflow is undefined.   I believe "-fwrapv" does that.  I don't see it listed in the -O<n> summaries so it's not clear to me whether that's turned on by -O3 or by some other levels as well.
I wonder how many other C standard violations exist in SIMH.  Linux is notorious for them; it might well be that SIMH is similar, which given its similar age would not be all that surprising.  There's a nice paper (from MIT I think) explaining dozens of popular assumptions about what C compilers do that are not valid, and it mentions how to make the compiler put up with most of them.

**Comment by markpizz** [comment]
At one time, I worked through the VAX simulator to make it uint32 clean, specifically to avoid legacy overflow behaviors.  This involved many changes and although the result was capable of booting my VMS environment, the change set was so large that I couldn't, in good conscience, make that the primary VAX version.  This was effectively a new VAX which needed a much more robust exercise to prove that this result was still a VAX.  DEC historically leveraged AXE to do this.

**Comment by bscottm** [comment]
@markpizz: Never got an answer about AXE.

**Comment by bscottm** [comment]
@rcornwell: I was being as tactful possible. My overall objective, by far, was to make the build system cross-platform, make it less painful to compile on Windows and avoid the extra acrobatics required to download obsolete libraries, extra setup and compatibility issues with the hand regenerated VS solution files.  With CMake, those solution files are automagically generated and it does support older versions of VS.

**Comment by bscottm** [comment]
@LegalizeAdulthood: It's going to take me a few days to migrate the CMake builder over, so please be patient. I'm testing out the build (vice just pulling stuff over and hoping it works.)

While I'm at it: I added a few shims to reduce MSVC deprecated POSIX libcall warnings. Should I include those or submit as a pull on a separate branch?

**Comment by pkoning2** [comment]
If that deprecated warning appears with the existing build procedures as well, or is unrelated to the CMake changes, then it would be cleanest to submit that separately.

**Comment by LegalizeAdulthood** [comment]
> the Makefile is pretty easy to add in new simulators.

The approach I'm taking in PR #33 is that there is a CMake function you invoke to add a simulator and this is something that can easily be imitated by looking at the existing simulator's CMakeLists.txt.  The function is also well documented for advance use cases.

Additionally, CMake has a huge user community (e.g. stack overflow) where you can almost always find the answer to your question by googling for it.  The same cannot be said of Makefiles because every project's makefile is bespoke one-off unique to that project.

> Traditionally SimH supported VMS, Unix and Windows

How important is VMS support?  Who is using it?  AFAIK, CMake does not natively support VMS as a target platform.

> There is no simulator specific testing cases to validate whether a simulator compiles or not.

Well, sure there is.  The continuous integration builds verify that the simulators at least compile.

> Add CTEST might be useful, however the testcases have to be written. And this might not be as simple as it sounds.

CTest is just a way to say "this test equals run this command".  It can provide dashboards and history and whatnot if you want, but really it's not much different from what is hand-coded into the makefile currently.

**Comment by LegalizeAdulthood** [comment]
@bscottm I too had added compile flags to eliminate a bunch of deprecated warnings from MSVC.  Since I used a function to encapsulate the details of adding a simulator this is located in one place.

**Comment by LegalizeAdulthood** [comment]
@pkoning2 I believe the existing MSVC projects have the similar defines to silence those deprecation warnings, but they don't appear in the makefile IIRC.

**Comment by rcornwell** [comment]
For CMake I would have a top level CMakelist.txt file that looks for the required packages and configures flags and variables to tell what is available. In each simulator directory there would be their own CMakelist.txt file. This would build just the simulator. The top level CMakelist.txt should take a list of simulators you wish to build or if none given build all. With CMake it would be possible to alter the build of individual simulators based on features available. So if a simulator has some graphics support, but SDL is not installed either it can be built without graphics support, or if this makes no sense, report an error.

**Comment by bscottm** [comment]
@pkoning2: Silencing the deprecation is The Wrong Thing To Do because MS can (and has) fully deprecated things like `stricmp` (which MS prefers to be `_stricmp`.) They aren't hard to work around.

**Comment by bscottm** [comment]
@rcornwell: I'll push my `cmake` branch up to github later and you can take a look at what I've been privately maintaining for ~3 years. It's pretty close to what you describe. Some deviations:

- Needed dependencies are built, e.g., SDL2 and SDL2_ttf (and png and zlib and ...)
- The current list of simulators is automagically extracted from the Makefile. If the Makefile changes, you need python3 to regenerate the simulator `CMakeLists.txt`.
- All of the build products end up living under the `cmake/build-*` subdirectories.

Not sure if I put in the ability to limit which sims are built from the CMake command line.

**Comment by LegalizeAdulthood** [comment]
> @pkoning2, @LegalizeAdulthood : Silencing the deprecation is The Wrong Thing To Do because MS can (and has) fully deprecated things like `stricmp` (which MS prefers to be `_stricmp`.) 

They aren't going to be removing these entry points any time soon because of the huge amount of software that would break.

> They aren't hard to work around.

What are you suggesting?  I would rather not see every invocation of `stricmp` bracketed with an `#ifdef`

**Comment by rcornwell** [comment]
Not sure I understand the need for Python to build a simple CMakelist.txt. I would drop this as just another complexity added to build the product.

**Comment by bscottm** [comment]
@rcornwell: Regenerating the CMake infrastructure from the Makefile was a requirement from @markpizz. @markpizz wrote a C-based "regenerator"; I prefer scripting languages for things like parsing and regenerating (easier to debug and maintain, IMHO, Linux distros have python3 natively installed.)

Since everyone changes the Makefile, the python3-based regenerator has to stay for the time being.

Going forward, if CMake is the new build system, then it can be ditched. But let's not put a cart before a horse.

**Comment by bscottm** [comment]
@LegalizeAdulthood: It's relatively straightforward to replace `fileno` with `host_os_fileno`. Extract from `sim_os_renames.h` (in my repo..):

````C
#if !defined(SIM_OS_RENAMES_H)

#if !defined(USE_ISO_NAMES)
/* Version identification as to when these ISO-compliant names showed up is an educated guess. */
#  if (defined(_WIN32_WINNT) && (_WIN32_WINNT >= _WIN32_WINNT_WIN7)) || (defined(_MSC_VER) && (_MSC_VER >= 1900))
#    define USE_ISO_NAMES
#  endif
#endif /* USE_ISO_NAMES */

#if defined(USE_ISO_NAMES)
#define host_os_chdir _chdir
#define host_os_fileno _fileno
/* ... */
#else
#define host_os_chdir _chdir
#define host_os_fileno _fileno
/* ... */
#endif
````

**Comment by bscottm** [comment]
@LegalizeAdulthood, @pkoning2: I also took a pass through the code to reduce the number of printf() format warnings. See [sim_printf_fmts.h][https://github.com/bscottm/simh-cmake/blob/vax_cc_branchless/sim_printf_fmts.h] on the `vax_cc_branchless` branch.

**Comment by markpizz** [comment]
@bscottm,

Your stuff looks like progress.

A few things:

1) HAVE_DLOPEN=xxx should be changed to SIM_HAVE_DLOPEN=xxx.
2) simh only depends on pcre.h and it seems that although this file exists on the system, the compiles are not then invoked with HAVE_PCRE_H defined.
3) You aren't building all the simulators.  Specifically, I notice that for some reason you're not building the SEL32 simulator.  Maybe you should build all directories found with an exclusion list of directories to avoid (i.e. display, .github, .travis, BIN, doc, .etc)
4) On Ubuntu Linux, I happened to not have installed the OS provided libsdl2-ttf-dev package installed, your procedure tried to fetch and build sdl2-ttf, but that invocation of cmake_builder failed.  I installed the OS provided package and started over and that worked.  Your build of the library failed.  You should really prefer the OS provided packages since, when they are available, they are validated by the OS packager.
5) Your information in README-cmake.md about WinPcap and Npcap is at least out of date.  WinPcap is obsolete and Npcap is fully supported.  Building simh with Pcap ethernet support on essentially all platforms only requires pcap.h to be found.  The interface to the kernel level packet capture and injection capabilities are dynamically loaded at runtime.  When pcap.h is available, compiles should be invoked with HAVE_PCAP_NETWORK, USE_SHARED and USE_READER_THREAD.  In your README-cmake.md, you specifically say that flex and bison (winflexbison) are needed to compile and build the pcap library.  Since this never needs to happen for perfectly fine networking support, the extra tool chain dependencies are not needed either.
6) On Linux you don't seem to detect the needed include for tun/tap support, and thus compile with HAVE_TAP_NETWORK defined.
7) Things might get further on Windows once the effort to build pcap is removed...
8) On MacOS, it initially needs gnu-getopt to be installed which isn't mentioned in your README-cmake.md.  Once that's installed, the cmake-builder.sh script blows up:
```
marks-mac-mini:cmake mark$ ./cmake-builder.sh 
./cmake-builder.sh: line 173: realpath: command not found
usage: dirname string [...]
./cmake-builder.sh: Can't determine SIMH top-level source directory.
Did this really happen?
```


Just a slightly humorous side note:  A key motive for the cmake activity is due to the crazy/complicated mess at the top of the simh makefile.  Now, instead, there is a different possibly more crazy/complicated mess in the cmake directory and additional logic/pieces scattered all over the directory structure.  Hooray for folks to now be able to use cmake with this extended set of tool chain elements to get off the ground.

**Comment by bscottm** [comment]
@markpizz:  You're welcome to tweak the patch. Honestly, you're a significant disincentive for me to contribute to open-simh.

**Comment by markpizz** [comment]
@bscottm, I don't make any decisions about what goes into open-simh.

You have, by far, made the most progress on cmake support of anyone.

Earlier in this discussion, @pkoning2 said:
> Please note: right now we have nothing other than some discussion. I'd suggest the creation of a complete implementation, not just skeletons. (We have skeletons, but those are not ready to become replacement build systems.) It doesn't need to do more than the current Makefile, though more (such as packaging) has been suggested and would be valuable. But it shouldn't do less, and it should be shown to work on at least the major platforms (Linux, various BSDs, Mac, Windows). And it should handle, cleanly, the optional libraries that a number of the emulators can use -- that in fact is one of the problem areas in the existing system.

So, since I wrote and have maintained the current build facilities, I have the best view of how well a new approach is achieving what @pkoning2 said and given that, I've taken my own time to access what you've put together.  If/when you or someone else makes further progress, I may find the time to review it.  I will not be making changes.

Many have had powerful discussion views about how things should work, but only you and a couple of others have actually tried to implement something.  You should be lauded for your efforts.

**Comment by rcornwell** [comment]
@markpizz I think the point of CMake is that it has a better syntax for all the logic that is in the top of the current makefile. Also it can make the correct decisions on any supported platform. If the top level CMakeList.txt is written correctly, then each simulator can get what features are available and that it can use. This moves much of the simulator specific stuff on the top into each simulators CMakeList.txt file.

**Comment by bscottm** [comment]
@markpizz: Is the tap/tun interface support supposed to be "on" by default? I've got it turned off by default.

**Comment by markpizz** [comment]
> @markpizz: Is the tap/tun interface support supposed to be "on" by default? I've got it turned off by default.

If it is available, it is always on.  Likewise for all the other network packet types (pcap, nat, udp, tun/tap, vde).  Disable network and none are available.

**Comment by bscottm** [comment]
@markpizz: No concerns about the attack surface that presents?

**Comment by markpizz** [comment]
> @markpizz: No concerns about the attack surface that presents?

Please elaborate your concerns.

**Comment by LegalizeAdulthood** [comment]
@bscottm I wouldn't worry about a python script to regenerate CMake builds from the makefile unless the owners of this repository (**NOT** markpizz) say it is a requirement.  The expectation is that the makefile will be removed once the CMake build has achieved feature parity.

Regarding your suggestion for `stricmp`, etc., API calls my only reservation is that people contributing new code aren't going to realize that they need to write these SIMH specific variants for common API calls.  As I say, MS is not going to remove those entry points and it's extremely common across projects to simply disable the deprecation warning with the macro definition, which is why MS puts that macro definition there in the first place.

**Comment by markpizz** [comment]
@bscottm said:

> @markpizz: No concerns about the attack surface that presents?

I'll fully elaborate my concerns:  I have NONE.

Adding the ability at compile time for a user to send and receive packets via various different mechanisms does nothing to the attack surface of a simulator.

If a user chooses to use any particular packet mechanism, there might then be some theoretical concern about attacks arriving via that particular mechanism, but until that happens there is 0 added attack surface.   if the host system has the potential ability for different packet mechanisms then they should be included at build time.  As I vaguely recall, the ability to completely disable networking at build time was added based on your concerns.

On all platforms platforms, using any of the packet mechanisms besides udp and nat can require admin/root privileges for the process doing this.  Anyone running in that context should always have concerns about attacks.  Such concerns is part of their admin job and usually is managed in either system or network firewalls.   

When I say "all platforms", I include:

 - Windows - Installing Npcap has the option of requiring admin rights to access the packet facilities.  The admin doing the Npcap install makes the choice as to how they want to allow access.
 - Some unix/unix-like platforms start with packet devices which default to allow only root access, but can have the access rights on the packet capture devices to be changed and thus allow non-root access.  Enabling non-root access to packet capture facilities requires root/admin rights.

The tun/tap packet paradigm is very commonly used by simulator users on the systems that support it.  That functionality has been in simh's Ethernet functionality going back about 17 years.  Your concern today about attack surface is the first mention of any concern like that.  So, I once again ask you to elaborate.

**Comment by pkoning2** [comment]
> @markpizz: No concerns about the attack surface that presents?

Are you talking about network attacks on the emulated OS?  That seems quite unlikely, except perhaps if you're running an old Unix with TCP implemented AND you have the emulation host exposed to the wild Internet.  But emulated systems of any kind are unlikely malware targets -- how many script kiddies have VAX based scripts, for example, never mind B5500 or PDP11 ones?
Consider that there is a whole community of DECnet users around the Internet (HECnet) and it doesn't seem that it's a subject of attacks. And for good reason; it would be hard enough to get in at the data link level, harder still at the higher layer protocols, and in most cases that wouldn't get you in the emulated OS environment.  Consider that most of those operating systems were designed with good security -- VMS, RSTS, TOPS-10 and TOPS-20 all were designed to be secure timesharing systems in hostile (i.e., university) environments.
Last but not least, you only get any of this stuff if you enable the relevant networking emulated devices and then configure them to do packet level connections to your real hardware.  If you don't want your emulated system on the network, don't enable network devices.
I'm confident enough of the SIMH code to say that a disabled or unconfigured emulated networking device does not activate any host networking activity.  But of course, as a final recourse you could build with that stuff turned off -- but doing so should not be the default.

**Comment by bscottm** [comment]
@LegalizeAdulthood: I get the maintenance issues with having function call renames, although they're easy to catch. Personally, I strive for warning-free code, with MS "deprecated" APIs being an example. They're not hard to catch, though, and easily fixed.

**Comment by bscottm** [comment]
@pkoning2: Generally, yes, there is an attack surface with a lot of network features exposed. I grant you that there's a configuration step required. Just wanted to sanity check.

The VAXen, in particular, can be exposed to the "wild" Internet -- otherwise, you won't be able to download updated NetBSD packages, as an example.

**Comment by LegalizeAdulthood** [comment]
> @LegalizeAdulthood: I get the maintenance issues with having function call renames, although they're easy to catch. Personally, I strive for warning-free code, with MS "deprecated" APIs being an example. They're not hard to catch, though, and easily fixed.

Well the general fix that's been arrived at by most of the world is to simply define the macro that suppresses the warnings.  Seriously, they are never going to remove those API entry points because of the compatibility burden.

**Comment by Rhialto** [comment]
The makefile is rather convoluted...

When I last looked, for Darwin, LTO seems explicitly turned on.

For some (many/all?) other cases, there is a `NO_LTO = 1` both in the
then-part and the else-part of a condition (around line 1210). Then
there is a variable `LTO_EXCLUDE_VERSIONS` which also causes `NO_LTO = 1`.
And around line 520 there is a test which checks if gcc seems to support
LTO, and disables it if it seems not.

In any case, if I compile with the makefile from the repo (and not
edited as by pkgsrc), I see no signs of LTO. That's on NetBSD/amd64 with
gcc 7 or 8.

**Comment by Rhialto** [comment]
On Tue 11 Oct 2022 at 01:40:08 -0700, Rhialto The M. wrote:
> The makefile is rather convoluted...

I am not sure why this message got re-sent...

**Comment by barjac** [comment]
I have been loosely following this thread which seems to have stalled.
Does this mean that the CMake alternative is now completed and available somewhere?
If so could someone point me to it so I can make test package builds.
I maintain open-simh in Mageia and would like to make the switch as and when it's ready for use.
Thanks.

**Comment by pkoning2** [comment]
It's been submitted in pull request 53.  That's just about ready to be merged but it hasn't merged yet.

**Comment by XVilka** [comment]
Fixed in https://github.com/open-simh/simh/commit/8b14bb69be608fa60d17b1433e42b677d575e3f6
